ALTER TABLE {IFW_TBL_CONTENT} ADD COLUMN tags_deleted TEXT NOT NULL AFTER user_groups;
INSERT INTO {IFW_TBL_SYS_PREFERENCES}(preference, content) VALUES('{C_PREF_WELCOME_CODE}', "Welcome, $strWelcomeName");
ALTER TABLE {IFW_TBL_CONTENT} ENGINE = MyISAM;
ALTER TABLE {IFW_TBL_CONTENT} ADD FULLTEXT(title, content);
