ALTER TABLE {IFW_TBL_AREAS} DROP template_group_id, DROP page_template_id, DROP site_template_id, DROP comment_template_id;
ALTER TABLE {IFW_TBL_AREAS} ADD theme_path TEXT NOT NULL;
ALTER TABLE {IFW_TBL_AREAS} ADD layout_style VARCHAR(50) NOT NULL DEFAULT '';
DROP TABLE IF EXISTS maj_components;
DROP TABLE IF EXISTS maj_custom_links;
DROP TABLE IF EXISTS maj_sys_template_types;
DROP TABLE IF EXISTS maj_sys_templates;
DROP TABLE IF EXISTS maj_template_defaults;
DROP TABLE IF EXISTS maj_template_groups;
INSERT INTO {IFW_TBL_SYS_PREFERENCES}(preference, content) VALUES('{C_PREF_DEFAULT_THEME}', "default");
