INSERT INTO {IFW_TBL_SYS_PREFERENCES}(preference, content) VALUES('{C_PREF_COMMENT_NOTIFY_AUTHOR}', '1');
INSERT INTO {IFW_TBL_SYS_PREFERENCES}(preference, content) VALUES('{C_PREF_ARTICLE_NOTIFY_ADMIN}', '1');

DROP TABLE IF EXISTS {IFW_TBL_USER_STATS};
CREATE TABLE IF NOT EXISTS {IFW_TBL_USER_STATS} (
  user_email VARCHAR( 100 ) NOT NULL ,
  comment_count INT NOT NULL DEFAULT '0',
  article_subscriptions TEXT NOT NULL,
  PRIMARY KEY (user_email)
);
