ALTER TABLE {IFW_TBL_CONTENT} DROP INDEX title;
ALTER TABLE {IFW_TBL_CONTENT} ADD FULLTEXT title(title);
ALTER TABLE {IFW_TBL_CONTENT} ADD FULLTEXT content(content);
ALTER TABLE {IFW_TBL_CONTENT} ADD FULLTEXT title_content(title, content);
ALTER TABLE {IFW_TBL_CONTENT} CHANGE title title VARCHAR( 125 ) NOT NULL;
ALTER TABLE {IFW_TBL_AREAS} CHANGE name name VARCHAR( 125 ) NOT NULL;
ALTER TABLE {IFW_TBL_PERMISSION_PROFILES} ADD publish_article TEXT NOT NULL AFTER create_article;
UPDATE {IFW_TBL_PERMISSION_PROFILES} SET publish_article = create_article;
INSERT INTO {IFW_TBL_SYS_PREFERENCES}(preference, content) VALUES('{C_PREF_ARTICLE_REVIEW_EMAIL}', '1');
